### ISSUE TITLE
Transitioning from Babel to SWC Rust WASM

### ISSUE THREAD

**Issue by jantimon** [jantimon/next-yak#110]
![Yak goes SWC](https://github.com/jantimon/next-yak/assets/4113649/78af6dd7-f539-44ed-aeac-2b2247c584d9)

### Current Status
- We currently use a Babel plugin for next-yak: [babel-yak-plugin.ts](https://github.com/jantimon/next-yak/blob/main/packages/next-yak/loaders/babel-yak-plugin.ts)
- A Rust version using SWC is in development: [lib.rs](https://github.com/jantimon/next-yak/blob/feature/rust/packages/yak-swc/yak_swc/src/lib.rs)

### Reasons for Transition
1. SWC API offers advanced capabilities:
   - Better control over variable scopes thank to SWCs variable ID system
   - Easier to control child visiting with `visit_mut_children_with`
   - Simplified handling of Template Literals

2. Performance improvements with Rust and WASM
3. Right now next-yak runs before the default Next.js (SWC) compilation with babel -> leading to compiling everything twice

### Open Questions 
1. We have to decide wether we will support for `.yak` with SWC

### Next step:

1. Testing injected comments (maybe with [helpful improvements by SWC team](https://github.com/swc-project/swc/issues/9149))

**Comment by jantimon** [comment]
if the migration to swc is successful we should add it to the swc test suite:

https://x.com/kdy1dev/status/1809491396241539113?s=46&t=ekpYTshuIMZzGwibybTgkA

and add @swc/counter as dependency 

https://x.com/swc_rs/status/1808501197504151593?s=46&t=ekpYTshuIMZzGwibybTgkA

**Comment by jantimon** [comment]
![a exited yak sitting on a flying rocket - the letters SWC are written on the rusty rocket in yellow letters](https://github.com/jantimon/next-yak/assets/4113649/85ed5a72-b4f7-413e-b1c8-d9158902bde9)

PR: https://github.com/jantimon/next-yak/pull/116/

Missing parts:

- [ ] `.yak.ts` imports 
- [ ] inject the yak import (`import __styleYak from "./file.yak.module.css!=!./file?./file.yak.module.css";`)
- [ ] fix [css-mixin-nested](https://github.com/jantimon/next-yak/blob/feature/rust/packages/yak-swc/yak_swc/tests/fixture/css-mixin-nested/output.tsx)
- [ ] configure in withYak
- [ ] ensure all test cases from babel are covered
- [ ] add special thanks to @kdy1 to readme for his relentless support
- [ ] remove all TODOs
- [ ] fix playground
- [ ] update docs

**Comment by kdy1** [comment]
I really love the image

**Comment by paulm17** [comment]
More a comment than anything else.  But why SWC instead of OXC?  I remember it was said that OXC was 3x faster?

Or are there any other factors at play here?  

Btw, I don't know anything about this except that I find it fascinating and watching this unfold gives me something else to look at and research later.  So thanks for making it public.  🚀

**Comment by jantimon** [comment]
Unfortunately PR will break the next-yak support for stackblitz:

> Wasm version of SWC does not support plugins

The SWC team might improve that but it sounds like it's not that easy for them:
https://github.com/swc-project/swc/issues/3934
