### ISSUE TITLE
upgrade vitest

### ISSUE THREAD

**Issue by jantimon** [jantimon/next-yak#126]
Allmost all our security warnings are caused of vitetest.

I don't see any risk for our users as it is only a dev dependency but we should probably take a look into upgrading it anyway:

[![dependabot](https://github.com/user-attachments/assets/54e0c73c-4cfb-4784-921b-8c2986aa1896)]( https://github.com/jantimon/next-yak/security/dependabot)

**Comment by Mad-Kat** [comment]
Could also come from the docs & playground as they also have vite

**Comment by jantimon** [comment]
good point (totally forgot about that)
