### ISSUE TITLE
Keyframe animations defined after usage not resolved correctly

### ISSUE THREAD

**Issue by jantimon** [jantimon/next-yak#166]
When keyframe animations are defined after their usage in styled components, particularly within nested css template literals in conditional statements, the plugin throws an "Unsupported template literal in css expression" error. This issue occurs even though the keyframes are defined in the same file.

## Minimal Reproducible Example

```typescript
import { css, keyframes, styled } from "next-yak";

const Card = styled.div<{ $flipped: boolean }>`
  position: relative;
  transform-style: preserve-3d;
  transform: rotateY(180deg);

  ${({ $flipped = false }) =>
    $flipped
      ? css`
          animation: ${cardFlip} 0.275s forwards linear;
        `
      : css`
          animation: ${cardUnflip} 0.275s forwards linear;
        `}
`;

// Keyframes defined after usage
const cardFlip = keyframes`
  0% {
    transform: rotateZ(0deg) rotateY(180deg);
  }
  50% {
    transform: rotateZ(-10deg) rotateY(90deg);
  }
  100% {
    transform: rotateZ(0deg) rotateY(0deg);
  }
`;

const cardUnflip = keyframes`
  0% {
    transform: rotateZ(0deg) rotateY(0deg);
  }
  50% {
    transform: rotateZ(-10deg) rotateY(90deg);
  }
  100% {
    transform: rotateZ(0deg) rotateY(180deg);
  }
`;
```

## Error Message

```
Unsupported "cardFlip" template literal in css expression - only css`` allowed
```

## Expected Behavior

The keyframe animations should be resolved and usable within the styled component, even when they are defined after their usage in the file.

The issue likely stems from the order of processing in the AST traversal.

**Comment by jaggli** [comment]
It works, if the keyframe calls are before the Card definition, but it doesn't work if they're below (in the file) - so ordering seems to be an issue.
