### ISSUE TITLE
Nextjs 15

### ISSUE THREAD

**Issue by Mad-Kat** [jantimon/next-yak#181]
As next.js 15 is [officially released](https://nextjs.org/blog/next-15) we should update our version of the SWC plugin to match [the version of next.js 15](https://plugins.swc.rs/versions/range/13).

Additionally we should have some discussions on how we want to handle different versions of next.js influencing our plugin especially when we have small changes or bugs that should? be backported.

**Comment by jantimon** [comment]
It will be a breaking change - so backporting changes to the previous release should be doable in most cases :)

I would say we should only backport once people ask for it or after we did a lot of changes

**Comment by jantimon** [comment]
#196 allows using next-yak for Next 15 however it looks like we will have to upgrade to SWC 5.x for the upcoming Next 15.0.3 release
