### ISSUE TITLE
Allow limited polymorphic components through `attrs`

### ISSUE THREAD

**Issue by jantimon** [jantimon/next-yak#184]
Currently, next-yak does not support [polymorphic components](https://styled-components.com/docs/api#as-polymorphic-prop) (switching elements via an `as` prop) like styled-components does.

This was an intentional decision for the several reasons:

1. **Semantic HTML & Accessibility**: When you create a component like `styled.button`, you're making a deliberate choice about its semantic meaning and accessibility behavior. HTML elements have built-in keyboard handling, focus management, and ARIA roles. Allowing arbitrary element switching via `<Button as="div">` can lead to semantically incorrect HTML structure and break critical accessibility features. This affects not just user experience but also SEO and assistive technology compatibility.

2. **Component Contract**: Styled components often include specific event handlers and props tied to their element type (like `disabled` for buttons). Unrestricted element switching can break these assumptions and create confusing behavior:

```tsx
// What happens to disabled and onClick when switched to div?
const Button = styled.button`
  &:disabled { opacity: 0.5 }
`
```

3. **TypeScript Complexity**: Supporting unrestricted polymorphic components requires extremely complex type definitions that need to handle all possible HTML elements while maintaining proper prop typing. This complexity makes the types harder to maintain, debug, and understand for users

However, we stumbled across some legitimate use cases where controlled element switching is valuable, like for example consistent button/link stylings

Rather than implementing unrestricted polymorphic components, we could use the `attrs` API for element switching at component definition time:

```tsx
import { styled } from "next-yak";

// Base button component
const Button = styled.button`
  padding: 8px 16px;
  background: blue;
  color: white;
  border-radius: 4px;
  /* ... more styles ... */
`

// Need to reuse button styles for a link
const LinkButton = styled(Button).attrs({
  as: 'a'
})``;

// Usage
<Button onClick={() => {}}>Normal Button</Button>
<LinkButton href="/about">Link that looks like a button</LinkButton>
```

**Comment by devbrains-com** [comment]
Allowing polymorphic components is not a clean approach in my opinion. When you define styles for a specific component or element, you don't think of someone changing your HTML tag, later on.

Either you start styling a dynamic element (e.g.: styled.any), where you know it will change later on and the types are accordingly (including "as" for example), or you have a dynamic mixin (not supported right now), which is somehow the same as it's not component or element specific.

Unfortunately, dynamic mixins are not possible with the current setting, but there may be another approach to doing something similar.

**Comment by rvetere** [comment]
I agree on most points that polymorphic components are problematic. But in certain cases like our link/button implementation, i would love to solve it with that feature.

A button is a button, but the `ButtonLink` is a button receiving the styles of "Link" and vise versa. As we cannot solve that edge case with dynamic mixins anymore, i would appreciate having this solved with `as`. Of course, we can also solve this as components, but the refactoring would be quite heavy then.

**Comment by jaggli** [comment]
In UI-architecture in general, only the smallest amount of overlapping code should be shared among components. Defining and reverse-overriding is a common anti-pattern and should be avoided.

I do not fully agree, of this being a valid use-case, because it hides most of the important complexity, like the different needs of a button and a link, here in particular. Those should be two different components and share the styles only. Already here in this case, we already need to distinguish between element styles, different browser default styles and visual styles.

```tsx
import { styled } from "next-yak";

const buttonStyles = css`
  padding: 8px 16px;
  background: blue;
  color: white;
  border-radius: 4px;
  /* ... more styles ... */
`

// Button component
const Button = styled.button`
  /* overriding browser defaults */
  border: 0;  

  /* visual styles */
  ${buttonStyles};

  /* button specific styles */
  /* ... */
`

// ButtonLink component
const ButtonLink = styled.a`
  /* overriding browser defaults */
  text-decoration: none;

  /* visual styles */
  ${buttonStyles};

  /* button-link specific styles */
  /* ... */
`

// Usage
<Button onClick={() => {}}>Normal Button</Button>
<LinkButton href="/about">Link that looks like a button</LinkButton>

```

So in order to promote minimal-dependency and more explicit code, I suggest to **not** introduce this dangerous `"as"` pattern - because this will lead ultimately to non-refactorable codebases and unnecessary complexity. I never liked it in `styled-components` and I like the fact, `next-yak` does not support it by design.

**Comment by jantimon** [comment]
Thanks everyone for the discussion

After reading your feedback, I agree that we should stick with our current approach of not supporting polymorphic components for now.

I am closing this for now, though I'm happy to reconsider if there are good reasons for it
