### ISSUE TITLE
Support unpure style tags ? 

### ISSUE THREAD

**Issue by laem** [jantimon/next-yak#221]
In my @cartesapp I make heavy use of styled-components to wrap multiple element styled in one component only. 

Just tried converting my codebase to yak, I got this error : 

```
 Selector "h1" is not pure (pure selectors must contain at least one local class or id)

  1 | .ExplanationWrapper {
> 2 |   h1 {
    |   ^
  3 |     margin-top: 0;
  4 |   }
  
  ````

Is this a limitation when using Yak ? In this case, I believe it should be noted on the README as a big limitation when migrating. 
  
This is the file in question : 

```
import { styled } from 'next-yak'

export const ExplanationWrapper = styled.div`
	h1 {
		margin-top: 0;
	}
	ol {
		padding-left: 1.5rem;
	}
	margin: 1vw 1rem;
	a {
		color: var(--darkestColor);
	}
	p {
		margin: 1rem 0;
		line-height: 1.4rem;
	}
`
export const ContentSection = styled.section`
	position: relative;
	h1 {
		margin: 0;
		margin-left: 0.1rem;
	}
`
```

**Comment by laem** [comment]
I suppose I'm doing something wrong because it seems to work with the Stackblitz demo. 

![image](https://github.com/user-attachments/assets/3327cecd-b0c6-45c4-a39b-172587e80161)

**Comment by jantimon** [comment]
`Selector "h1" is not pure (pure selectors must contain at least one local class or id)`

is an error from next.js (postcss-modules-local-by-default) but the code you showed should definitely work - if it does not work it would be a bug in next-yak or next.js

can you show me a reproduction somewhere!

**Comment by laem** [comment]
Thanks ! I'm running the migration here https://github.com/cartesapp/cartes/pull/704
Some routes work in dev, some others don't. I'll investigate :)

**Comment by laem** [comment]
Looks like it solved the problem, thanks !
