### ISSUE TITLE
css prop support

### ISSUE THREAD

**Issue by laem** [jantimon/next-yak#77]
Hi, very interesting project. I'm making a heavy use of styled-components's `css` prop. 

E.g. 

```
<div css={`
background: grey; 
strong {color: pink}
`}>my <strong>content</strong></div>
```. 

Is it supported ?

**Comment by Mad-Kat** [comment]
Hey @laem 

Thank you for opening this issue. We don't support [styled-components css prop](https://styled-components.com/docs/api#css-prop) yet, but it would definitely be doable.

Out of curiosity - How did you find out about this project?

**Comment by laem** [comment]
Hi, good question. I don't remember how I found it. Maybe "linaria + next" in Kagi + some more links on github  ?

**Comment by jantimon** [comment]
it might be a great addition for very simple layout components 

e.g. instead of abstractions like this one:

![a stack component](https://github.com/jantimon/next-yak/assets/4113649/30ab8650-8f2b-40fc-a6a2-298b4290b418)

**Comment by laem** [comment]
Yes, I often use it for components that need just a bit of styling, do not justify creating a new ui component file, and also that are not used twiced in the app.

**Comment by paulm17** [comment]
I found this repo via: https://www.joshwcomeau.com/react/css-in-rsc/#the-list-goes-on-10

When will https://github.com/jantimon/next-yak/pull/78 be merged in?  

Thanks!

**Comment by jantimon** [comment]
I'll discuss it with @Mad-Kat today and will give you an update

**Comment by jantimon** [comment]
css prop has some complicated edge cases

however we discussed internally and decided to ship a first version which won't cover all edge cases soon

**Comment by jantimon** [comment]
short update - #78 took some rounds to find the optimal solution but I believe it is getting really close to be released

**Comment by jantimon** [comment]
Released in next-yak 0.2.0

**Comment by laem** [comment]
Seems to be gone but soon reintroduced #169

**Comment by Mad-Kat** [comment]
Exactly. With the move from Babel to SWC, we lost the ability. Should be finished after my holidays

**Comment by jantimon** [comment]
@laem we added it back to swc with next-yak 2.3.0

**Comment by laem** [comment]
In my migration from styled-components here https://github.com/cartesapp/cartes/pull/704, it looks to me that the css prop is not working in lots of cases. I'm unable to isolate a failing one from a working one for now, but I'll try to provide an example. Maybe something to do with nesting inside the css template literal ? With css= props inside styled.x components ? To be investigated. 

I'm converting lots of css props to styled.x proper components. Which is quite a heavy migration, and more verbose. Well at least I don't have to isolate them in "use client" files like it used to be with styled-components.

**Comment by Mad-Kat** [comment]
Hey @laem thank you for trying it out and starting the migration. I'm not quite sure what the problems are, as the PR changes quite a lot of things (especially formatting) that makes it hard to spot what actually changed with the migration to `next-yak`. Can you point me to a file where it doesn't work? I would love to have a look around and see how we can help you.

**Comment by laem** [comment]
Yes the PR is massive, I'll try to isolate a component and show you.

**Comment by laem** [comment]
I sorted out the PR problem : a sed command added a space to all the lines, making every tsx file change. 

I've also isolated a "css prop" that was not working, changed to a styled.span https://github.com/cartesapp/cartes/pull/704/commits/50eb166886ebe8ef0d62711f589cadcb8ea7e9a0

It should help you see if there is a problem or if my expectations of your css prop is wrong.

**Comment by jantimon** [comment]
This code should work:

```tsx
<span
	css={css`
		display: inline-block;
		width: 1.8rem;
	`}
></span>
```

I added it to your base page and it works correctly

**Comment by laem** [comment]
> Sometimes you forgot to import css maybe that's an issue?

Yes I'm progressively adding the missing imports, since with styled-components no import was needed. I added the css`` automatically with sed but couldn't add the import automatically by the same way. 

> I added it to your base page and it works correctly

Strange, it didn't work for me. Hence the rewrite to styled.span in the commit that I have linked.

**Comment by laem** [comment]
In this file https://github.com/cartesapp/cartes/blob/21fc8f2a43b7d43b9ac9138030f89234e6831eeb/app/itinerary/ClickItineraryInstruction.tsx, the `css` prop does not work. The img is rendered with its full svg width. 

![image](https://github.com/user-attachments/assets/459df4d1-b08e-46b7-8f04-60614937d010)

![image](https://github.com/user-attachments/assets/3c203b23-b1d1-466c-a8a9-6872e9117f9c)

**Comment by Mad-Kat** [comment]
Thanks for the reproduction. We saw that once you disable the react compiler it works as planned. 

We didn't look into the react compiler yet, but now we definitely should. The assumption is that the compiler runs before our plugin has the chance to run and that doesn't work well with the non-transpiled code.

Can you verify that it works on your side without the react compiler?

**Comment by laem** [comment]
> Can you verify that it works on your side without the react compiler?

Yes ! It seems to resolve the missing css= props' css. But I was starting to rely quite seriously on the compiler, as it turns out that disabling it created infinite loops. It must have added useMemos that are needed for the app to work. Proving its interest by the way :)

**Comment by laem** [comment]
Some more feedback on the matter. 

When I try to use a .babelrc file*, the default proposed by the [nextjs doc](https://nextjs.org/docs/pages/building-your-application/configuring/babel), I get new errors. 

```
[ Server ] Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
  <div css={function} children={[...]}>
           ^^^^^^^^^
```

![image](https://github.com/user-attachments/assets/b1340003-83ab-4a03-8a59-091bf4b65d50)

\* I'm trying to add a babel file to support the `with {type: json}` that is added by contentlayer2. It's unrelated to next-yak.

**Comment by laem** [comment]
My guess is that the withYak function adds a swc parsing to the next-config, which cannot read the `with` import assertion produced by contentlayer2.

**Comment by laem** [comment]
Hi @Mad-Kat, I'm wondering if support of React Compiler is planned, or not. Thanks !

**Comment by jantimon** [comment]
could you please create a dedicated issue for that topic?

I guess we will have to reach out to the react compiler devsand ask them if we can do the compiling right before the jsx transformation
